### ISSUE TITLE
Quellcode unvollständig

### ISSUE THREAD

**Issue by DO1JLR** [nikilauda1983/sw_optimize#1]
Wäre cool den aktuellen Quellcode tatsächlich zu sehen.

Danke

**Comment by jondeans** [comment]
It would. But if he did that you could make a better version and that would make him sad :(

**Comment by cnnranderson** [comment]
This has been completed. As per a previous ticket, note that I will be contributing to the project as per the original author's allowance.

I'm also going to making a few improvements across the board such as:
- Algorithm optimization
- Build and Tooling updates (gradle/intellij)
- Cleaning up and organizing some of the misc files in the repo
- Updating readme's and help documentation
- Cleaning up the code and removing a lot of static accessed methods
